name: Train model

on:
  push:
    # Trigger only when pushing tags (required for release step to work)
    tags:
      - 'v*'  # Example: v1.0, v2.0.1

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r data/requirements.txt

      - name: Train Model
        run: python data/loanmodel.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: loanmodel-pkl
          path: data/model/loan-moodel.pkl

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: data/model/loan-moodel.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}