name: Train model

on:
  push:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r loandemo\data\requirements.txt

      - name: Train Model
        run: python loandemo/loan-model.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: loanmodel-pkl
          path: data/model/loan-moodel.pkl

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: data/model/loan-moodel.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}